import dotenv from "dotenv";
dotenv.config();
const { PASETO_PRIVATE_KEY, PASETO_PUBLIC_KEY, PORT, AWS_DEFAULT_REGION,
    AWS_ACCESS_ID,
    AWS_SECRET_KEY, BUCKET_NAME } = process.env;

export {
    PASETO_PRIVATE_KEY, PASETO_PUBLIC_KEY, PORT, AWS_DEFAULT_REGION,
    AWS_ACCESS_ID,
    AWS_SECRET_KEY,
    BUCKET_NAME
};
