version: "3.9"

services:
  backend:
    image: your-dockerhub-username/photoshare-backend:latest
    container_name: photoshare-backend
    restart: always
    ports:
      - "80:4000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      JWT_SECRET: ${JWT_SECRET}
